feat:User CRUD
DendraScience/dendra-web-ui pull request #35
Opened 2023-03-07 15:41 UTC by ergjustin

## Related Issues:
[USERS CRUD](https://github.com/orgs/DendraScience/projects/1/views/1?pane=issue&itemId=21895579)

## Main Changes:

- Users list
- User create || if person without same email create new person with given data
- User update
- User delete

## Steps To Test:

1. Login 
2. Navigate to http://localhost:3000/users
3. Check users list, create, update and delete

2023-03-07 21:22 UTC, devincowan requested changes
@ergjustin nice work!
A few questions for you, but overall this looks great

2023-03-07 21:22 UTC, devincowan commented on src/pages/users/_userId/index.vue
> +    <v-btn
Should Managers be able to edit the information of other managers? Seems questionable--I think Managers should be able to edit Users, but not other Managers.
probably a good Q for @jscottsf

2023-03-08 17:23 UTC, ergjustin commented on src/pages/users/create.vue
> +          <user-detail v-model="instance" :editing="editing" :create="true" />
UserDetail component is used in two places. 
1.	Create user (password field is required)
2.	Edit user (password not required)

For this reason, I used flag to differentiate Create or Edit

2023-03-15 20:25 UTC, devincowan commented on src/pages/users/_userId/index.vue
> +    <v-btn
making a note here that @ergjustin discussed with Scott and we will just use the `$can` ability to check for manager editing

2023-03-16 14:45 UTC, devincowan commented on src/pages/users/_userId/index.vue
> +    <v-btn
@ergjustin I created a separate issue for the `$can` CASL ability check (to ensure managers can't edit other managers/sys_admins)
https://github.com/DendraScience/dendra-web-ui/issues/41

2023-03-16 14:45 UTC, devincowan approved these changes
Looks good!

2023-03-16 18:14 UTC, devincowan commented
Making some notes here from our call today

We talked about having this check use `$can` instead of using `auth`
https://github.com/DendraScience/dendra-web-ui/blob/dev-justin/src/components/MainNavigationDrawer.vue#L120

2023-03-20 20:20 UTC, ergjustin commented
Related Issues: [USER CRUD](https://github.com/DendraScience/dendra-web-ui/issues/30#issuecomment-1472496970)

Except password reset everything else finished.

2023-03-21 15:41 UTC, devincowan requested changes
Thanks for all of the updates @ergjustin!
A few issues that we can discuss on our call

2023-03-21 15:41 UTC, devincowan commented on src/components/UsersSearch.vue
> +    optionItems: ['Deactivated'],
I think we should add the ability to filter to show _only is_active users_ as well.

2023-03-21 15:41 UTC, devincowan commented on src/components/UsersSearch.vue
> +            <template #item.indicators="{ item }">
nice work Justin, looks good!

2023-03-21 18:28 UTC, devincowan commented on src/components/MainNavigationDrawer.vue
> +              can: ['read', 'users'],
making a note that we also want this nav section to be hidden when you "drill down" into an Org. And we want to change the name `Admin Section` => `Admin`

2023-03-21 18:32 UTC, devincowan commented on src/components/UsersSearch.vue
> +    optionItems: ['Deactivated'],
note we decided today not to call users "disabled"

2023-03-21 18:36 UTC, devincowan commented on src/components/UsersSearch.vue
> -                $regex: `${escapeRegExp(search)}`,
Scott will patch the $regex so that we don't get a type error for int

2023-03-21 19:24 UTC, devincowan commented on src/components/UsersSearch.vue
> -                $regex: `${escapeRegExp(search)}`,
Okay, decided to leave this as is for now and implement Ngrams later...

2023-03-27 17:46 UTC, devincowan commented on src/components/UserPasswordEdit.vue
> +          this.$bus.$emit(this.editStatus ? 'edit-status' : 'status', {
Why did you add this check for `edit-status` message?

2023-03-27 17:53 UTC, devincowan reviewed
looking really good, couple questions...

2023-03-27 17:53 UTC, devincowan commented on src/layouts/editor.vue
>          >
we should also disable/hide the "Cancel" button during `isLoading`...as it is right now, if you cancel while save is occurring, the new user still gets created.

2023-03-27 18:06 UTC, ergjustin commented on src/components/UserPasswordEdit.vue
> +          this.$bus.$emit(this.editStatus ? 'edit-status' : 'status', {
We use two different kinds of StatusBar, it depends upon the layouts.
default: - status
editor: - edit-status

UserPasswordEdit component used in two layouts.
User settings (default layout)
User details (editor layout)

2023-03-27 19:06 UTC, devincowan commented on src/components/UserPasswordEdit.vue
> +          this.$bus.$emit(this.editStatus ? 'edit-status' : 'status', {
got it thanks

2023-03-27 19:11 UTC, devincowan approved these changes
looks good @ergjustin!

2023-03-27 19:11 UTC, devincowan commented on src/components/MainNavigationDrawer.vue
> +              can: ['read', 'users'],
admin section will still be shown to standard `users` (in addition to `managers` and admins) but perhaps that is our intent

2023-04-04 18:09 UTC, devincowan commented on src/components/MainNavigationDrawer.vue
> +              can: ['read', 'users'],
we discussed today, @ergjustin will make this `can` -> `canCreate`

2023-04-04 23:08 UTC, devincowan approved these changes
thanks @ergjustin!

2023-04-04 23:09 UTC, devincowan commented
I think we are finally good to merge this unless there are other pending issues I'm not aware of

2023-04-10 18:03 UTC, merged